[nrf noup] cmake: Adopted to new multi image approach
nrfconnect/sdk-mcumgr pull request #2
Opened 2019-11-15 08:49 UTC by tejlmand

This PR introduces the use of the new principle for creating multi image build.

It reverts the only nordic specific commit, so instead of merging this PR, I suggests that we simply upmerge our fork and drop all Nordic only commits.
Alternatively, we start following upstream SHA in our manifest.

---------
All occurrences of ${IMAGE} have been removed in order to adopt to the
new strategy used for multi image builds.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

2019-11-15 14:36 UTC, SebastianBoe requested changes
NACK

WIP

2019-11-18 16:08 UTC, mbolivar commented
Same deal as tinycbor -- no diff from zephyrproject-rtos, so just point there

2019-11-19 10:31 UTC, tejlmand commented
Closing as: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1508
now points upstream

2019-11-19 10:33 UTC, tejlmand commented
Closing as: NordicPlayground/fw-nrfconnect-nrf#1508
now points upstream

2019-11-19 10:33 UTC, closed without merging